spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
    open-in-view: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: bam_schema
      hibernate:
        format-sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:postgresql://localhost:5432/dvo_db?currentSchema=bam_schema
    username: postgres
    password: postgres
    hikari:
      schema: bam_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS bam_schema
      connection-timeout: 10000